"""Added account table

Revision ID: 348968e8cc39
Revises: 
Create Date: 2022-04-05 20:57:16.451246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348968e8cc39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('idToken', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idToken')
    )
    op.create_index(op.f('ix_user_idToken'), 'user', ['idToken'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.idToken'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_id'), 'resource', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_id'), table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_user_idToken'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
