"""Added account table

Revision ID: 488177710689
Revises: 
Create Date: 2022-04-08 21:07:07.888573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488177710689'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('idToken', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idToken')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_idToken'), 'user', ['idToken'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idResource', sa.Integer(), nullable=False),
    sa.Column('idOwner', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('startTime', sa.String(), nullable=False),
    sa.Column('endTime', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['idOwner'], ['user.idToken'], ),
    sa.ForeignKeyConstraint(['idResource'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_id'), 'reservation', ['id'], unique=False)
    op.create_table('user_and_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.String(), nullable=False),
    sa.Column('idResource', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idResource'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['idUser'], ['user.idToken'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_and_resource_id'), 'user_and_resource', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_and_resource_id'), table_name='user_and_resource')
    op.drop_table('user_and_resource')
    op.drop_index(op.f('ix_reservation_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_user_idToken'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('resource')
    # ### end Alembic commands ###
